### ISSUE TITLE
Comments from testing

### ISSUE THREAD

**Issue by Mmintyyy** [cms-opendata-workshop/workshop-lesson-cmssw#1]
It took me around 1 h 15 mins to complete this lesson from start to finish using virtual machine. Some comments below:

### CMSSW (front page)
- Docker: link not working

### Installation and Execution

**Setting up your CMSSW area**
- "validation instructions": link not working

### The Source
- Time estimates are missing
- It could be helpful to highlight the changes made in the code, so that it would be easier to do them yourself (especially if the user is not able to copy paste from local to virtual machine)
- I was not familiar with vi so I needed to google for some help with the commands, but with the help of this site I managed well: https://phoenixnap.com/kb/how-to-exit-vim
	○ Depending on the expected level of the users, one might consider explaining the needed commands in the text

**Comment by caredg** [comment]
Thanks @Mmintyyy I have fixed the links (now that are available) and considered some of your comments which will go in in the next push.  Unfortunately, i did not find a convincing way of highlighting pieces of code in an already highlighting environment within what carpentry offers, but I did try to make it clearer what the changes are.
In included a note on a cheatsheet for vi.
I am reluctant to explain every shell command (if that is what you mean), as the tutorial will get really cluttered.  But thinking of these, I added the unix shell for novice optional tutorial in the list of pre-exercises.
