### ISSUE TITLE
02: comments

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-cmssw#2]
Comments for https://cms-opendata-workshop.github.io/workshop-lesson-cmssw/02-installation/index.html

- [x] As people tend to copy-paste without reading, it would be good to make graphically clear that the first command for docker is only for docker.... e.g.

If you completed the lessons on virtual machines or Docker you already have a working CMSSW area.

- If you are using VM:

  -  turn on your virtual machine and go to the right shell according to the validation instructions (maybe a screenshot)

- If you are using docker

  - start the container with: ...
 
- [x] You could also try to compile (build) the code. We use scram, the release management tool used for CMSSW: -> We use  scram, the release management tool used for CMSSW, to compile (build) the code:

- [x] is there a reason to have rev=21 in this link: https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookEdmUtilities?rev=21

- [x] maybe spell out EDM for event data model (for CMS) or leave EDM out from "EDM utilities" and use just "utilities"

**Comment by caredg** [comment]
Thanks @katilp.  I will incorporate these fixes in the next push.  I guess the rev usage was to make sure there are no additional utilities that perhaps are not available in the older release, but it is not super important.

**Comment by caredg** [comment]
closed by e107bcb7c81d9eb8adad9bbc17f34019ab012c8c
