### ISSUE TITLE
From the mattermost chat: how to find where different object methods come from

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-cmssw#4]
From [the mattermost chat](https://mattermost.web.cern.ch/cmsopendatatheo/channels/cmssw-pre-exercise):

> am I right if I understand   reco::MuonCollection   as a collection of reconstructed muon classes? I can see  isValid()  and  energy()  methods being applied, but where are they extracted from?
> 
> yes you are right about the reco::MuonCollection.  The question about the methods is a good one.  During the workshop we will cover some of this to develop certain intuition.  Here's where the intricacy starts, and where one can begin using the CMSSW code repository itself as documentation.  
> - For instance, when you are asking for the validity of mymuons, which is actually a Handle object, you could probably intuitively think that there is a Handle.h class controlling that.  
> - So, you can search for Handle.h on the cmssw github repository and find the header of that class and, within it, this note.  
> - Then you realize that the Handle.h class inherits from the HandleBase class, whose header you can find in the same package.  If you explore that header, you will find where the method is actually implemented.  Note that I always choose the CMSSW_5_3_X branch of the repository.  
> - Now, for the energy() method, since it is not specific to muons, one can probably guess that these methods should be inherited from an upper class.  
> - Let's use LXR (the cross reference site that was mentioned in the introduction) this time, because it is easier to backtrack.  
>    - After you localize the Muon.h class, you can find this line, which points you a RecoCandidate class.  
>    - You can click on it to find the location of that class.  Among other mentions of such class, LXR will tell you that is in this line where it gets defined, which in turn (after you find out that there is no energy() method declared there) will point you to the LeafCandidate class; and you can keep doing that .... You will eventually arrive to the mother class, where these basic candidate methods are declared and implemented. 
>

**Comment by caredg** [comment]
referenced to new version
